### ISSUE TITLE
which version of gitbook

### ISSUE THREAD

**Issue by elvisbegovic** [wishtack/gitbook-printer#1]
For what version of gitbook this lib is ? 
ps:im trying new gitbook.com version and need pdf of content

**Comment by yjaaidi** [comment]
Hi @istiti ! Yes ! It has been made for the new gitbook.com ;)

**Comment by elvisbegovic** [comment]
@yjaaidi  would be helpfull to notify this on readme or project title thanks

**Comment by yjaaidi** [comment]
@istiti Done! 👍 Thanks!
