### ISSUE TITLE
Unable to generate for any gitbook

### ISSUE THREAD

**Issue by alexey-krylov** [wishtack/gitbook-printer#5]
For example:
https://docs.squidex.io

Running:

`gitbook-printer --base-url https://docs.squidex.io --summary-path ./SUMMARY.md`

Here is output:
![image](https://user-images.githubusercontent.com/953840/43134674-756d669c-8f4b-11e8-839b-4da447062bb1.png)

**Comment by alexey-krylov** [comment]
Forgot to git clone project first. It will be nice to add this to manual - first step: clone your doc repo

**Comment by yjaaidi** [comment]
Hi @alexey-krylov, in fact, you have to retrieve the SUMMARY.md from the repo.

Thank you for the feedback. I am gonna add this to the documentation.

The best way would probably to scrap the content from the URL instead of having to clone the repository but it's a little bit hacky for the moment.
